//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _19
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factory
    {
        public int Number { get; set; }
        public string SurnameCollector { get; set; }
        public string NameCollector { get; set; }
        public string PatronymicCollector { get; set; }
        public Nullable<int> CountOfManufacturedDetailsMonday { get; set; }
        public Nullable<int> CountOfManufacturedDetailsTuesday { get; set; }
        public Nullable<int> CountOfManufacturedDetailsWednesday { get; set; }
        public Nullable<int> CountOfManufacturedDetailsThursday { get; set; }
        public Nullable<int> CountOfManufacturedDetailsFriday { get; set; }
        public Nullable<int> CountOfManufacturedDetailsSaturday { get; set; }
        public Nullable<int> CountOfManufacturedDetailsSunday { get; set; }
        public string NameFactory { get; set; }
        public string TypeDetails { get; set; }
        public decimal PriceDetails { get; set; }
    }
}
